# Netlify Configuration
# Landing Page: Manual WhatsApp Atendimento

[build]
  # This is a static HTML/CSS site, no build step needed
  publish = "."
  command = ""

# Headers for security and performance
[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML - force fresh load
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/styles/*"
  [headers.values]
    # Cache CSS for 1 hour (shorter for development)
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache assets for 1 day (shorter for development)
    Cache-Control = "public, max-age=86400"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/videos/*"
  [headers.values]
    # Cache videos for 1 day
    Cache-Control = "public, max-age=86400"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    # Cache scripts for 1 hour
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"
